# 办公室网络
DOMAIN,firezone.nocode-tech.com
HOST-SUFFIX,nocode-tech.com
HOST-SUFFIX,nocode.mobi
HOST-SUFFIX,nocodetech.cn
DOMAIN,pgm-bp102bs17ul8kx5auo.pg.rds.aliyuncs.com
DOMAIN,pgm-bp1yip0491bx6c12zo.pg.rds.aliyuncs.com
HOST-SUFFIX,dev.nocode.com
HOST-SUFFIX,redis.rds.aliyuncs.com
HOST-KEYWORD,nocode
HOST-KEYWORD,readhub
HOST-SUFFIX,pg.rds.aliyuncs.com
HOST-SUFFIX,kibana.elasticsearch.aliyuncs.com
HOST-SUFFIX,public.elasticsearch.aliyuncs.com
HOST-SUFFIX,cn-hangzhou.elasticsearch.aliyuncs.com
IP-CIDR,10.3.56.0/24
IP-CIDR,47.99.68.12/32
IP-CIDR,106.75.213.145/32
IP-CIDR,106.75.214.133/32